images:
  default:
    path: <path to image file>
    type: png
  logo:
    path: <path to image file>
    type: jpeg

kv_store:
  "dock_name": <Dock Name>
  "timezone": "GMT"

code:
  path: <path to python code file>
